[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
