[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
evm_version = "paris"

[rpc_endpoints]
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[etherscan]
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
